config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'teasers#index'

  resources :teasers, :news, :actions, :houses
  resources :sponsors, only: [:new, :edit, :create]

  get 'admin', to: 'application#admin'
  get 'logout', to: 'application#logout'

end

app/models/action.rb
class Action < Post
  self.table_name = "actions"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < Post
  self.table_name = "houses"
end

app/models/news.rb
class News < Post
  self.table_name = "news"
end

app/models/post.rb
class Post < ApplicationRecord
  extend ::Enumerize
  self.inheritance_column = nil

  enumerize :type, in: { full_width_image: 0, half_width_image: 1, no_image: 2 }

  validates :title, :description, :type, presence: true

  mount_uploader :image, ImageUploader

  def get_url
    if url && url.empty?
      self
    else
      url
    end
  end

  def get_button_text
    if button_text && button_text.empty?
      "Show more"
    else
      button_text
    end
  end
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord

  validates :name, :image, :url, presence: true

  mount_uploader :image, ImageUploader
end

app/models/teaser.rb
class Teaser < Post
  self.table_name = "teasers"
end

app/controllers/actions_controller.rb
class ActionsController < PostsController

  def klass
    Action
  end

  def key
    :action
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin
    redirect_to root_path if authenticate
  end

  def logout
    session[:admin] = false
    redirect_back(fallback_location: root_path)
  end

protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      admin_username = Rails.application.secrets.admin_username
      admin_password = Rails.application.secrets.admin_password
      session[:admin] = true if (username == admin_username && password == admin_password)
    end
  end
end

app/controllers/houses_controller.rb
class HousesController < PostsController

  def klass
    House
  end

  def key
    :house
  end

end

app/controllers/news_controller.rb
class NewsController < PostsController

  def klass
    News
  end

  def key
    :news
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:admin, :new, :create, :edit, :update, :destroy]

  def index
    @posts = klass.all
    @sponsors = Sponsor.all
  end

  def show
  end

  def new
    @post = klass.new
  end

  def create
    @post = klass.new(post_params)

    if @post.save
      # TODO: redirect to index
      redirect_to @post, notice: "The post was created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Update successful"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Post destroyed"
  end

  private

    def post_params
      params.require(key).permit(:title, :content, :image, :type, :description, :url, :button_text)
    end

    def find_post
      @post = klass.find(params[:id])
    end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :find_sponsor, only: [:edit, :update, :destroy]
  before_action :authenticate, only: [:admin, :new, :create, :edit, :update, :destroy]

  def new
    @sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(sponsor_params)

    if @sponsor.save
      redirect_to root_path, notice: "Sponsor was created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @sponsor.update(sponsor_params)
      redirect_to root_path, notice: "Sponsor was updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @sponsor.destroy
    redirect_to root_path, notice: "Sponsor destroyed"
  end

  private

    def sponsor_params
      params.require(:sponsor).permit(:name, :image, :url)
    end

    def find_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

end

app/controllers/teasers_controller.rb
class TeasersController < PostsController

  def klass
    Teaser
  end

  def key
    :teaser
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/actions/edit.html.erb
<div class="container">
  <h1>Edit <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/actions/index.html.erb
<div class="container-fluid index-container">
  <% @posts.each do |post| %>
    <%= render 'shared/post', post: post %>
  <% end %>
</div>

app/views/actions/new.html.erb
<div class="container">
  <h1>Add <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/actions/show.html.erb
<%= render 'shared/show_post' %>

app/views/houses/edit.html.erb
<div class="container">
  <h1>Edit <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/houses/index.html.erb
<div class="container-fluid index-container">
  <% @posts.each do |post| %>
    <%= render 'shared/post', post: post %>
  <% end %>
</div>

app/views/houses/new.html.erb
<div class="container">
  <h1>Add <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/houses/show.html.erb
<%= render 'shared/show_post' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>OdbudowaDomku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/news/edit.html.erb
<div class="container">
  <h1>Edit <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/news/index.html.erb
<div class="container-fluid index-container">
  <% @posts.each do |post| %>
    <%= render 'shared/post', post: post %>
  <% end %>
</div>

app/views/news/new.html.erb
<div class="container">
  <h1>Add <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/news/show.html.erb
<%= render 'shared/show_post' %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <%= render 'shared/error_messages' %>

  <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "Choose a category" }) %><br>
  <%= f.select :type, Post.type.options, { prompt: "Choose post type" } %><br><br>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: "Type the post title here" %><br>
  <br>
  <p>Apart from plain text, in DESCRIPTION and CONTENT you can use basic html and css: style text, add links and even images (with img tags and external urls as src). You can use any classes from <%= link_to "bootstrap framework", "https://getbootstrap.com/", target: "_blank", rel: "nofollow" %>.</p>
  <%= f.label :description %><br>
  <%= f.text_area :description, size: "60x12",
    placeholder: "Description will appear on the post's list in the category you chose. If you chose full_width_image, keep it very short, or text might be not fully visible on the page. For half_width_image, it should be quite short too, otherwise it might look bad. It can be longer for no_image." %><br><br>
  <%= f.label :content %><br>
  <%= f.text_area :content, size: "60x12", placeholder: "Content will appear on the new page, after clicking 'show more' button. You can skip it - in this case there will be no 'show more' button at all." %><br><br>
  <%= f.label :image %><br>
  <p>Please use only horizontally oriented images. Standard rectangular format is preferred. Square or vertically oriented images might be cut in case of full_width_image, and they might take too much of the page area with half_width_image.</p>
  <%= f.file_field :image %><br><br>

  <%= f.label :button_text %><br>
  <p>If you want to change the default "Show more" button text, type it here (please keep it short)</p>
  <%= f.text_field :button_text, placeholder: "Type the post title here" %><br><br>

  <%= f.label :url %><br>
  <p>By default, clicking "Show more" button will redirect to page with post content. If you want it to redirect to different page, please paste url here.</p>
  <%= f.text_field :url, placeholder: "Type the post title here" %><br><br>

  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<div class="container show-container">
  <article class="post">
    <div class="row">
      <div class="col">
        <h1><%= @post.title %></h1>
        <p><%= raw SafeHtml.relaxed(@post.content) %></p>
        <% if @post.image_url %>
          <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-fluid postImg" %>
        <% end %>
        <% if session[:admin] %>
          <%= link_to edit_post_path(@post), class: "btn btn-default" do %>
            <span class="btn btn-warning" aria-hidden="true">Edit post</span>
          <% end %>
          <%= link_to @post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" do %>
            <span class="btn btn-danger" aria-hidden="true">Delete post</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </article>
</div>

app/views/shared/_error_messages.html.erb
<% if post.errors.any? %>
  <div>
    <p><%= pluralize(post.errors.count, "error") %> prevented it from being saved.</p>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <%= render 'shared/error_messages', post: @post %>

  <%= f.select :type, Post.type.options, { prompt: "Choose post type" } %><br><br>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: "Type the post title here" %><br>
  <br>
  <p>Apart from plain text, in DESCRIPTION and CONTENT you can use basic html and css: style text, add links and even images (with img tags and external urls as src). You can use any classes from <%= link_to "bootstrap framework", "https://getbootstrap.com/", target: "_blank", rel: "nofollow" %>.</p>
  <%= f.label :description %><br>
  <%= f.text_area :description, size: "60x12",
    placeholder: "Description will appear on the post's list in the category you chose. If you chose full_width_image, keep it very short, or text might be not fully visible on the page. For half_width_image, it should be quite short too, otherwise it might look bad. It can be longer for no_image." %><br><br>
  <%= f.label :content %><br>
  <%= f.text_area :content, size: "60x12", placeholder: "Content will appear on the new page, after clicking 'show more' button. You can skip it - in this case there will be no 'show more' button at all." %><br><br>
  <%= f.label :image %><br>
  <p>Please use only horizontally oriented images. Standard rectangular format is preferred. Square or vertically oriented images might be cut in case of full_width_image, and they might take too much of the page area with half_width_image.</p>
  <%= f.file_field :image %><br><br>

  <%= f.label :button_text %><br>
  <p>If you want to change the default "Show more" button text, type it here (please keep it short)</p>
  <%= f.text_field :button_text, placeholder: "Type the post title here" %><br><br>

  <%= f.label :url %><br>
  <p>By default, clicking "Show more" button will redirect to page with post content. If you want it to redirect to different page, please paste url here.</p>
  <%= f.text_field :url, placeholder: "Type the post title here" %><br><br>

  <%= f.submit %>

<% end %>

app/views/shared/_nav.html.erb
<div class="container-fluid nav-container">
  <div class="row no-gutters position-relative">
    <div class="col">
      <nav>
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <%= link_to 'Strona główna', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Aktualności', news_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Odbudujmy 3/4', actions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Osiedle', houses_path, class: "nav-link" %>
          </li>
        </ul>

        <% if session[:admin] then %>
          <%= link_to logout_path, class: "position-absolute editBtn" do %>
            <span class="btn btn-warning" aria-hidden="true">Log out</span>
          <% end %>
        <% end %>

      </nav>
    </div>
  </div>
</div>

app/views/shared/_post.html.erb
<article class="postContainer position-relative">
  <div class="row no-gutters">
    <div class="col">

      <div class="d-flex flex-wrap justify-content-center align-items-center <%= post.type %> postWrapper">

        <% if post.image_url %>
          <%= image_tag post.image_url.to_s, alt: "Image", class: "img-fluid postImg" %>
        <% end %>

        <div class="post d-flex flex-wrap justify-content-center align-items-center">
          <h2 class="title"><%= post.title %></h2>
          <p class="description">
            <%= raw SafeHtml.relaxed(post.description) %>
          </p>
          <% if !post.content.empty? || (post.url && !post.url.empty?) %>
            <%= link_to post.get_button_text, post.get_url, class: "btn btn-outline-light" %>
          <% end %>
        </div>

        <% if session[:admin] %>
          <%= link_to [:edit, post], class: "btn btn-default position-absolute editBtn" do %>
            <span class="btn btn-warning" aria-hidden="true">Edit post</span>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</article>

app/views/shared/_show_post.html.erb
<div class="container show-container">
  <article class="post">
    <div class="row">
      <div class="col">
        <h1><%= @post.title %></h1>
        <p><%= raw SafeHtml.relaxed(@post.content) %></p>
        <% if @post.image_url %>
          <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-fluid postImg" %>
        <% end %>
        <% if session[:admin] %>
          <%= link_to [:edit, @post], class: "btn btn-default" do %>
            <span class="btn btn-warning" aria-hidden="true">Edit post</span>
          <% end %>
          <%= link_to @post, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" do %>
            <span class="btn btn-danger" aria-hidden="true">Delete post</span>
          <% end %>
        <% end %>
      </div>
    </div>
  </article>
</div>

app/views/sponsors/_form.html.erb
<%= form_for @sponsor, html: { multipart: true } do |f| %>

  <%= render 'shared/error_messages', post: @sponsor %>

  <%= f.label :name %><br>
  <%= f.text_field :name, placeholder: "Type the sponsor name here" %>
  <br><br>
  <%= f.label :image %><br>
  <p>Please use rectangular image of small size</p>
  <%= f.file_field :image %>
  <br><br>
  <%= f.label :url %><br>
  <%= f.text_field :url, placeholder: "Paste url to sponsor's page here" %>
  <br><br>

  <%= f.submit %>

<% end %>

app/views/sponsors/edit.html.erb
<div class="container">
  <h1>Edit sponsor</h1>
  <%= render 'form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/sponsors/new.html.erb
<div class="container">
  <h1>Add sponsor</h1>
  <%= render 'form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/teasers/_sponsor.html.erb
<div class="col-sm-3">
  <%= image_tag sponsor.image_url.to_s, alt: "Image", class: "img-fluid postImg" %>
  <%= link_to sponsor.name, sponsor.url, target: 'blank' %>
</div>

app/views/teasers/edit.html.erb
<div class="container">
  <h1>Edit <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/teasers/index.html.erb
<div class="container-fluid index-container">
  <% @posts.each do |post| %>
    <%= render 'shared/post', post: post %>
  <% end %>

  <div class="row">
    <% @sponsors.each do |sponsor| %>
      <%= render 'sponsor', sponsor: sponsor %>
    <% end %>
  </div>

</div>

app/views/teasers/new.html.erb
<div class="container">
  <h1>Add <%= @post.class.name %></h1>
  <%= render 'shared/form' %>
  <%= link_to "Back", root_path %>
</div>

app/views/teasers/show.html.erb
<%= render 'shared/show_post' %>